# Make hydra

dataset:
  name: chess_keypoints
  #  path: "/kaggle/input/chess-keypoint-dataset/" <- for kaggle
  path: 'data/' # <- for training locally
  train_size: 0.999
  batch_size: 10
  num_classes: 2 # Chess + background
  num_keypoints: 4

model:
  lr: 0.001
  epochs: 4 # 4
  lr_step: 2
  gamma: 0.1

# 0 for CPU training, 1 for GPU training
gpus: 1

logging:
  weights_path: "weights/"
  wandb_logs: "outputs/"

threshold:
  score: 0.7